import { Inter } from "next/font/google";
import "./globals.css";


const fontSans = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata = {
  title: "Documate AI",
  description: "Generated by create next app",
  generator: "v0.app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={fontSans.variable}>
      <body className="antialiased">
        
        {children}

        </body>

    </html>
  );
}
